### PR TITLE
multipleresulttypes

### PR DESCRIPTION
**Pull request by sammychinedu2ky**
Fix for these issues https://github.com/dotnet/AspNetCore.Docs.Samples/issues/76 and https://github.com/dotnet/AspNetCore.Docs.Samples/issues/77

### CODE REVIEW

**Review by tdykstra — APPROVED** [review]
Looks good!

**Comment by sammychinedu2ky** [comment]
> Looks good!

thanks

**Comment by tdykstra** [comment]
@sammychinedu2ky The sample illustrates the scenario where an endpoint has multiple possible result types -- can you add an endpoint that illustrates the code for endpoints that return only one type? Something like this but without the comments:

```
app.MapGet("/todos", async (TodoDb db)
{
    // This lambda now returns Ok<Todo[]>, a type that implements IEndpointMetadataProvider.
    // The framework will call Ok<Todo[]>.PopulateMetadata() when the endpoint is built,
    // which adds the necessary endpoint metadata to describe the HTTP response type.
    return TypedResults.Ok(await db.Todos.ToArrayAsync());
});
```

**Comment by sammychinedu2ky** [comment]
Ok @tdykstra  would do that

**Pull request merged**
