### PR TITLE
Use SQLite instead of EF In-Memory provider for testing

### LINKED ISSUE #91: Change Integration tests to use SQLite rather than SQL Server
https://github.com/dotnet/AspNetCore.Docs.Samples/tree/main/test/integration-tests/IntegrationTestsSample

See the sentence just above [this link](https://review.learn.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-7.0#customize-the-client-with-withwebhostbuilder)

The [EF-Core in-memory database provider](https://learn.microsoft.com/en-us/ef/core/testing/choosing-a-testing-strategy#in-memory-as-a-database-fake) can be used for limited and basic testing, however the [SQLite provider](https://learn.microsoft.com/en-us/ef/core/testing/choosing-a-testing-strategy#sqlite-as-a-database-fake) is the recommended choice for in-memory testing.

### PR DESCRIPTION
**Pull request by jvandertil**
Fixes #91

### CODE REVIEW

**Comment by jvandertil** [comment]
@Rick-Anderson I was a bit in doubt whether I should update the actual application (https://github.com/dotnet/AspNetCore.Docs.Samples/blob/main/test/integration-tests/IntegrationTestsSample/src/RazorPagesProject/Program.cs#L10) to use SQLite as well as that would probably ruin what we want to show in the snippet.

**Comment by jvandertil** [comment]
Alright, I've push a commit with that update and we can always revert it.

**Review by Rick-Anderson — APPROVED** [review]

**Comment by Rick-Anderson** [comment]
@jvandertil  nice work, looks good. Ready to merge?

**Comment by jvandertil** [comment]
@Rick-Anderson Yes, should be good to go!

**Pull request merged**
