### PR TITLE
Blazor Standalone WebAssembly with ASP.NET Core Identity

### LINKED ISSUE #230: Add Blazor WebAssembly standalone identity example
An example of how to use the new identity API with a standalone Blazor WebAssembly app.

### PR DESCRIPTION
**Pull request by JeremyLikness**
Fixes #230

### CODE REVIEW

**Comment by guardrex** [comment]
SPA and all of the other Identity samps should go in the main doc set sample repo here.

The reason we have the split is just to apportion the management of the samps. I don't watch the main doc set samples repo, but I do keep tabs on the Blazor samples repo. Also, you'll notice that I use a different versioning scheme to make sure that all samples are updated every release. That's not done with the main doc set samps.

**Comment by JeremyLikness** [comment]
Thanks for the clarifications. I'll move the Blazor one and switch to the other for SPA samples. I'm going to do Blazor Standalone WebAssembly, Blazor server rendered, Blazor wasm rendered, and blazor with external login. Should these all just be project folders under blazor-samples or do you want any sub-categories/directories in between?

**Comment by guardrex** [comment]
They go by versions, so you can place them into the `8.0` folder there SxS with the existing `BlazorWebAppEFCore` sample. That's the only one that I've updated to 8.0. The others in the 7.0 folder will get the same treatment ... they'll get folders in the `8.0` folder for their updates, but the Blazor Server 7.0 sample will become a Blazor Web App sample.

**Comment by guardrex** [comment]
... and if all goes well, you won't need to sweat them much after that. Each release, I'll update them. If I hit a problem, I'll give u a shout. You might only need to work on them again for some new security features that land in future releases if I can't understand what the updates should be.

Thus far with the EFCore sample, I've been able to update it each release without trouble, including for BWA. Note tho that it's still RC1 ... I'll get to it in a bit to take it to RC2, or I'll just jump in near release and make it final release 8.0. I'm still slammed at the moment with other work, so I'm not sure when I'll reach it. I'll get to it tho ...... ***eventually!*** 🗻⛏️😅

**Comment by JeremyLikness** [comment]
Closing to move sample.

**Pull request closed without merging**
