### PR TITLE
Refactor HTML

### PR DESCRIPTION
**Pull request by Rick-Anderson**

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@sammychinedu2ky  thanks for your great sample. I moved some of the code to a utilities file as I don't think we need to show it for the sample. I'll provide a link to the full code for those who are interested.

Feel free to PR this if you'd like to improve or clean up the code.

**Comment by sammychinedu2ky** [comment]
@Rick-Anderson you want me to move the utils class into a new file?

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson you want me to move the utils class into a new file?

Yes, and I'll bet you can find more ways to clean up the code, better conventions, names, etc.

**Comment by sammychinedu2ky** [comment]
Alright

**Pull request merged**
